/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as GoLinkIdRouteImport } from './routes/go.$linkId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AuthenticationSignUpRouteImport } from './routes/authentication/sign-up'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'
import { Route as DashboardLinksNewRouteImport } from './routes/dashboard/links.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLinksLinkIdEditRouteImport } from './routes/dashboard/links.$linkId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticationRoute,
} as any)
const GoLinkIdRoute = GoLinkIdRouteImport.update({
  id: '/go/$linkId',
  path: '/go/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticationSignUpRoute = AuthenticationSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)
const DashboardLinksNewRoute = DashboardLinksNewRouteImport.update({
  id: '/links/new',
  path: '/links/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLinksLinkIdEditRoute =
  DashboardLinksLinkIdEditRouteImport.update({
    id: '/links/$linkId/edit',
    path: '/links/$linkId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/authentication': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/new': typeof DashboardLinksNewRoute
  '/dashboard/links/$linkId/edit': typeof DashboardLinksLinkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/new': typeof DashboardLinksNewRoute
  '/dashboard/links/$linkId/edit': typeof DashboardLinksLinkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/authentication': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/new': typeof DashboardLinksNewRoute
  '/dashboard/links/$linkId/edit': typeof DashboardLinksLinkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/authentication'
    | '/dashboard'
    | '/authentication/login'
    | '/authentication/sign-up'
    | '/dashboard/settings'
    | '/go/$linkId'
    | '/authentication/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/links/new'
    | '/dashboard/links/$linkId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/authentication/login'
    | '/authentication/sign-up'
    | '/dashboard/settings'
    | '/go/$linkId'
    | '/authentication'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/links/new'
    | '/dashboard/links/$linkId/edit'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/authentication'
    | '/dashboard'
    | '/authentication/login'
    | '/authentication/sign-up'
    | '/dashboard/settings'
    | '/go/$linkId'
    | '/authentication/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/links/new'
    | '/dashboard/links/$linkId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  GoLinkIdRoute: typeof GoLinkIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/go/$linkId': {
      id: '/go/$linkId'
      path: '/go/$linkId'
      fullPath: '/go/$linkId'
      preLoaderRoute: typeof GoLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/authentication/sign-up': {
      id: '/authentication/sign-up'
      path: '/sign-up'
      fullPath: '/authentication/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/dashboard/links/new': {
      id: '/dashboard/links/new'
      path: '/links/new'
      fullPath: '/dashboard/links/new'
      preLoaderRoute: typeof DashboardLinksNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/links/$linkId/edit': {
      id: '/dashboard/links/$linkId/edit'
      path: '/links/$linkId/edit'
      fullPath: '/dashboard/links/$linkId/edit'
      preLoaderRoute: typeof DashboardLinksLinkIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLinksNewRoute: typeof DashboardLinksNewRoute
  DashboardLinksLinkIdEditRoute: typeof DashboardLinksLinkIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLinksNewRoute: DashboardLinksNewRoute,
  DashboardLinksLinkIdEditRoute: DashboardLinksLinkIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  GoLinkIdRoute: GoLinkIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
