/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as GoLinkIdRouteImport } from './routes/go.$linkId'
import { Route as AuthenticationSignUpRouteImport } from './routes/authentication/sign-up'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardLinksNewRouteImport } from './routes/_authenticated/dashboard/links.new'
import { Route as AuthenticatedDashboardLinksLinkIdEditRouteImport } from './routes/_authenticated/dashboard/links.$linkId.edit'

const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticationRoute,
} as any)
const GoLinkIdRoute = GoLinkIdRouteImport.update({
  id: '/go/$linkId',
  path: '/go/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSignUpRoute = AuthenticationSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksNewRoute =
  AuthenticatedDashboardLinksNewRouteImport.update({
    id: '/links/new',
    path: '/links/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksLinkIdEditRoute =
  AuthenticatedDashboardLinksLinkIdEditRouteImport.update({
    id: '/links/$linkId/edit',
    path: '/links/$linkId/edit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/authentication': typeof AuthenticationRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/links/new': typeof AuthenticatedDashboardLinksNewRoute
  '/dashboard/links/$linkId/edit': typeof AuthenticatedDashboardLinksLinkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/links/new': typeof AuthenticatedDashboardLinksNewRoute
  '/dashboard/links/$linkId/edit': typeof AuthenticatedDashboardLinksLinkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/authentication': typeof AuthenticationRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/links/new': typeof AuthenticatedDashboardLinksNewRoute
  '/_authenticated/dashboard/links/$linkId/edit': typeof AuthenticatedDashboardLinksLinkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/authentication'
    | '/dashboard'
    | '/authentication/login'
    | '/authentication/sign-up'
    | '/go/$linkId'
    | '/authentication/'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/links/new'
    | '/dashboard/links/$linkId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/authentication/login'
    | '/authentication/sign-up'
    | '/go/$linkId'
    | '/authentication'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/links/new'
    | '/dashboard/links/$linkId/edit'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/_authenticated'
    | '/authentication'
    | '/_authenticated/dashboard'
    | '/authentication/login'
    | '/authentication/sign-up'
    | '/go/$linkId'
    | '/authentication/'
    | '/_authenticated/dashboard/settings'
    | '/api/auth/$'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/links/new'
    | '/_authenticated/dashboard/links/$linkId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  GoLinkIdRoute: typeof GoLinkIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/go/$linkId': {
      id: '/go/$linkId'
      path: '/go/$linkId'
      fullPath: '/go/$linkId'
      preLoaderRoute: typeof GoLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/sign-up': {
      id: '/authentication/sign-up'
      path: '/sign-up'
      fullPath: '/authentication/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links/new': {
      id: '/_authenticated/dashboard/links/new'
      path: '/links/new'
      fullPath: '/dashboard/links/new'
      preLoaderRoute: typeof AuthenticatedDashboardLinksNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links/$linkId/edit': {
      id: '/_authenticated/dashboard/links/$linkId/edit'
      path: '/links/$linkId/edit'
      fullPath: '/dashboard/links/$linkId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardLinksLinkIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardLinksNewRoute: typeof AuthenticatedDashboardLinksNewRoute
  AuthenticatedDashboardLinksLinkIdEditRoute: typeof AuthenticatedDashboardLinksLinkIdEditRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardLinksNewRoute: AuthenticatedDashboardLinksNewRoute,
    AuthenticatedDashboardLinksLinkIdEditRoute:
      AuthenticatedDashboardLinksLinkIdEditRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  GoLinkIdRoute: GoLinkIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
